---
basePath: "/"
paths:
  /register/{type}:
    post:
      summary: "Register Customer"
      deprecated: false
      produces:
        - "application/json;charset=UTF-8"
      description: "Registers Customer to Merriment"
      operationId: "registerCustomer"
      responses:
        200:
          description: "Successful Response"
          schema:
            $ref: "#/definitions/RegisterCustomerResponse"
        201:
          description: "OK"
          schema:
            $ref: "#/definitions/ResponseMetaData"
        400:
          schema:
            $ref: "#/definitions/MerrimentError"
          description: "Y803 : eventName required<br>Y803 : callbackUrl required<br>Y800 : Invalid value for callbackUrl"
        401:
          description: "Unauthorized"
        404:
          description: "Not Found"
      parameters:
        - in: "path"
          name: "type"
          description: "type"
          type: "string"
          required: true
          enum:
            - "CareTaker"
            - "CareGiver"
        - schema:
            $ref: "#/definitions/RegisterCustomerRequest"
          in: "body"
          name: "registerCustomerRequest"
          description: "registerCustomerRequest"
          required: true
      tags:
        - "Customer"
      consumes:
        - "application/json"
definitions:
  RegisterCustomerRequest:
    type: "object"
    title: "RegisterCustomerRequest"
    properties:
      userName:
        readOnly: true
        type: "string"
      firstName:
        readOnly: true
        type: "string"
      lastName:
        readOnly: true
        type: "string"
      telephoneCode:
        readOnly: true
        type: "string"
      telephoneNumber:
        readOnly: true
        type: "string"
      emailAddress:
        readOnly: true
        type: "string"
      addressDetail:
        $ref: "#/definitions/AddressDetail"
  AddressDetail:
    type: "object"
    title: "Address"
    properties:
      addressLine1:
        readOnly: true
        type: "string"
      addressLine2:
        readOnly: true
        type: "string"
      country:
        readOnly: true
        type: "string"
      postCode:
        readOnly: true
        type: "string"
      townName:
        readOnly: true
        type: "string"
  ResponseMetaData:
    type: "object"
    title: "Response"
    properties:
      message:
        type: "string"
      statusCode:
        type: "string"
      errorDesInfo:
        type: "array"
        items:
          $ref: "#/definitions/MerrimentError"
  RegisterCustomerResponse:
    type: "object"
    title: "Register Customer Response"
    properties:
      userName:
        readOnly: true
        type: "string"
      firstName:
        readOnly: true
        type: "string"
      lastName:
        readOnly: true
        type: "string"
      telephoneCode:
        readOnly: true
        type: "string"
      telephoneNumber:
        readOnly: true
        type: "string"
      emailAddress:
        readOnly: true
        type: "string"
      addressDetail:
        $ref: "#/definitions/AddressDetail"
      errorDesInfo:
        type: "array"
        items:
          $ref: "#/definitions/MerrimentError"
  MerrimentError:
    type: "object"
    title: "ErrorDescription"
    properties:
      errorCode:
        type: "string"
      errorMessage:
        type: "string"
swagger: "2.0"
info:
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  contact:
    name: "API Development Team"
  title: "Register Customer"
  version: "1.0.0"
tags:
  - name: "Customer"
    description: "Customer API"