/*
 * Register Customer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.merriment.customerservice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ResponseMetaData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-11T12:38:18.583+01:00")
public class ResponseMetaData {
  @JsonProperty("message")
  private String message = null;

  @JsonProperty("statusCode")
  private String statusCode = null;

  @JsonProperty("errorDesInfo")
  private List<MerrimentError> errorDesInfo = null;

  public ResponseMetaData message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ResponseMetaData statusCode(String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
  @ApiModelProperty(value = "")
  public String getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }

  public ResponseMetaData errorDesInfo(List<MerrimentError> errorDesInfo) {
    this.errorDesInfo = errorDesInfo;
    return this;
  }

  public ResponseMetaData addErrorDesInfoItem(MerrimentError errorDesInfoItem) {
    if (this.errorDesInfo == null) {
      this.errorDesInfo = new ArrayList<MerrimentError>();
    }
    this.errorDesInfo.add(errorDesInfoItem);
    return this;
  }

   /**
   * Get errorDesInfo
   * @return errorDesInfo
  **/
  @ApiModelProperty(value = "")
  public List<MerrimentError> getErrorDesInfo() {
    return errorDesInfo;
  }

  public void setErrorDesInfo(List<MerrimentError> errorDesInfo) {
    this.errorDesInfo = errorDesInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseMetaData responseMetaData = (ResponseMetaData) o;
    return Objects.equals(this.message, responseMetaData.message) &&
        Objects.equals(this.statusCode, responseMetaData.statusCode) &&
        Objects.equals(this.errorDesInfo, responseMetaData.errorDesInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, statusCode, errorDesInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseMetaData {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    errorDesInfo: ").append(toIndentedString(errorDesInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

